# Generated by Django 2.0 on 2021-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/users/messi.jpg', upload_to='images/users/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
