# Generated by Django 2.0 on 2021-04-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_leavingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='自我简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='学校'),
        ),
    ]
