# Generated by Django 2.0 on 2021-02-25 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offline', '离线'), ('online', '在线'), ('erroe', '异常')], max_length=20, verbose_name='设备状态')),
                ('device_name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('device_id', models.CharField(max_length=100, verbose_name='设备ID')),
                ('belonged_product', models.CharField(max_length=30, verbose_name='所属产品')),
                ('product_type', models.CharField(max_length=30, verbose_name='设备类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
